import express from "express";
import upload from "../middleware/upload.js";
import { addNotificationController,deleteNotificationController,fetchNotificationController, sendNotificationController } from "../controller/notificationController.js";
import { uploadSingleFile } from "../middleware/uploadMiddleware.js";
const router=express.Router();
router.post("/fetchNotification",upload.none(),fetchNotificationController);
router.post("/addNotification",uploadSingleFile("photo"),addNotificationController);
router.post("/deleteNotification",upload.none(),deleteNotificationController);
router.post('/sendNotification', uploadSingleFile('photo'),sendNotificationController);
export default router;